import React from 'react';
import { jsPDF } from "jspdf";
import '../App.css';

function HandoverReports({ handovers }) {
    
    const handleDownloadPDF = (log) => {
        const doc = new jsPDF();
        doc.setFontSize(22);
        doc.setTextColor(0, 0, 0);
        doc.text("Official Shift Handover Report", 20, 20);
        
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text(`Generated by CMMS System on ${new Date().toLocaleString()}`, 20, 30);
        
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(`Outgoing Supervisor: ${log.supervisor}`, 20, 50);
        doc.text(`Shift Date: ${log.date}`, 20, 60);

        doc.setFontSize(16);
        doc.setTextColor(40, 40, 40);
        doc.text("Completed Tasks & Activities", 20, 80);
        doc.setFontSize(12);
        const tasksLines = doc.splitTextToSize(log.tasks || 'None logged.', 170);
        doc.text(tasksLines, 20, 90);

        let finalY = 90 + (tasksLines.length * 7);

        doc.setFontSize(16);
        doc.text("Outstanding Issues & Delays", 20, finalY + 15);
        doc.setFontSize(12);
        const issuesLines = doc.splitTextToSize(log.issues || 'None reported.', 170);
        doc.text(issuesLines, 20, finalY + 25);
        
        finalY = finalY + 25 + (issuesLines.length * 7);

        if (log.critical) {
            doc.setFontSize(16);
            doc.setTextColor(220, 38, 38);
            doc.text("CRITICAL INCIDENTS / RED FLAGS", 20, finalY + 15);
            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            const critLines = doc.splitTextToSize(log.critical, 170);
            doc.text(critLines, 20, finalY + 25);
        }

        doc.save(`Handover_Log_${log.supervisor.replace(' ', '_')}_${log.date}.pdf`);
    };

    return (
        <section id="handover-reports-section" className="component-section">
            <div className="card">
                <h2>Digital Handover Reports</h2>
                <div className="card-content">
                    {handovers.length === 0 ? (
                        <p className="empty-state">No handover logs generated yet.</p>
                    ) : (
                        <div className="handover-list" style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                            {handovers.map((log) => (
                                <div key={log.id} style={{ background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)', borderRadius: '12px', padding: '20px' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid var(--border-color)', paddingBottom: '15px', marginBottom: '15px' }}>
                                        <div>
                                            <h3 style={{ margin: '0 0 5px 0', color: 'var(--secondary-color)' }}>{log.supervisor}</h3>
                                            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Shift logged on: {log.date}</span>
                                        </div>
                                        <button onClick={() => handleDownloadPDF(log)} className="btn-secondary" style={{ padding: '8px 15px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                                            <i className="material-icons" style={{ fontSize: '1rem' }}>picture_as_pdf</i> Export PDF
                                        </button>
                                    </div>
                                    
                                    <div style={{ marginBottom: '15px' }}>
                                        <strong style={{ display: 'block', color: 'var(--text-muted)', marginBottom: '5px' }}>Completed Tasks:</strong>
                                        <p style={{ margin: 0, paddingLeft: '10px', borderLeft: '3px solid var(--accent-color)' }}>{log.tasks || 'None logged.'}</p>
                                    </div>

                                    <div style={{ marginBottom: '15px' }}>
                                        <strong style={{ display: 'block', color: 'var(--text-muted)', marginBottom: '5px' }}>Outstanding Issues:</strong>
                                        <p style={{ margin: 0, paddingLeft: '10px', borderLeft: '3px solid var(--warning-color)' }}>{log.issues || 'None reported.'}</p>
                                    </div>

                                    <div>
                                        <strong style={{ display: 'block', color: 'var(--text-muted)', marginBottom: '5px' }}>Critical Flags:</strong>
                                        <p style={{ margin: 0, paddingLeft: '10px', borderLeft: '3px solid var(--danger-color)', color: log.critical ? 'var(--text-light)' : 'var(--text-muted)' }}>
                                            {log.critical || 'No critical incidents.'}
                                        </p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </section>
    );
}

export default HandoverReports;
